services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: fuel_db
      POSTGRES_USER: fuel_user
      POSTGRES_PASSWORD: fuel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: