# Generated by Django 6.0.6 on 2026-06-10 00:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='core_fuelst_state_fa8a68_idx'), models.Index(fields=['price'], name='core_fuelst_price_560a45_idx')],
            },
        ),
    ]
