# Generated by Django 6.0.6 on 2026-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('haversine_miles', models.FloatField()),
                ('road_miles', models.FloatField()),
                ('road_factor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['origin_lat', 'origin_lng'], name='core_routed_origin__bcbe98_idx')],
                'unique_together': {('origin_lat', 'origin_lng', 'dest_lat', 'dest_lng')},
            },
        ),
    ]
