# Generated by Codex on 2026-06-10

from django.contrib.postgres.indexes import GistIndex
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0002_routedistance'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS core_fuelstation_location_gix '
                        'ON core_fuelstation USING GIST (location);'
                    ),
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS core_fuelstation_location_gix;',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='fuelstation',
                    index=GistIndex(
                        fields=['location'],
                        name='core_fuelstation_location_gix',
                    ),
                ),
            ],
        ),
    ]
